name: AlexLouie
favicon: null
layout_spectrum: 1
typography_spectrum: 0.27853
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.07242555567063391
  lightness: 0.3066018389072269
  saturation: 0.4278611906338483
  rhythmicContrast: 0.30630836193449795
purpose: []
